"""Behavioral CX tests.

These intentionally assert *ranges and recovered structure* rather than
frozen snapshot numbers: the sample is now generated by a documented model
(`src/generate_cx_dataset.py`), so the contract is "the pipeline recovers the
injected signal and the metrics stay internally consistent", not "metric == a
hand-typed constant".
"""

from __future__ import annotations

import importlib.util
import sys
import unittest
from pathlib import Path


LAB_ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = LAB_ROOT / "src"
sys.path.insert(0, str(SRC_DIR))


def load_module(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


validate_cx_data = load_module("validate_cx_data_test", SRC_DIR / "validate_cx_data.py")
build_cx_summary = load_module("build_cx_summary_test", SRC_DIR / "build_cx_summary.py")
cx_driver_analysis = load_module("cx_driver_analysis_test", SRC_DIR / "cx_driver_analysis.py")

SEGMENTS = {"Urban Commuters", "Touring Owners", "Performance Enthusiasts", "First-Time Owners"}


class CxMetricsTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.rows = validate_cx_data.load_rows()
        cls.summary = build_cx_summary.build_summary(cls.rows)

    def test_sample_data_passes_validation(self):
        self.assertEqual(validate_cx_data.validate_file(), [])

    def test_dataset_is_large_enough_for_statistics(self):
        self.assertGreaterEqual(self.summary["records"], 400)
        self.assertEqual(self.summary["records"], len(self.rows))

    def test_core_metrics_are_in_plausible_ranges(self):
        s = self.summary
        self.assertTrue(0.0 < s["customer_satisfaction_rate"] < 1.0)
        self.assertAlmostEqual(
            s["customer_satisfaction_rate_pct"],
            round(s["customer_satisfaction_rate"] * 100, 1),
            places=1,
        )
        self.assertTrue(1.0 <= s["journey_friction_index"] <= 5.0)
        self.assertTrue(0.0 <= s["follow_up_completion_rate"] <= 1.0)
        # internal consistency: segment volumes reconcile to the headline total
        self.assertEqual(
            s["weighted_feedback_volume"],
            sum(v["feedback_volume"] for v in s["segment_summary"].values()),
        )
        self.assertEqual(set(s["segment_summary"]), SEGMENTS)

    def test_monthly_trend_is_available_for_bi_reporting(self):
        trend = self.summary["monthly_trend"]
        self.assertGreaterEqual(len(trend), 6)
        self.assertEqual(list(trend), sorted(trend))
        for month in trend.values():
            self.assertGreater(month["feedback_volume"], 0)
            self.assertTrue(1.0 <= month["avg_satisfaction"] <= 5.0)


class CxDriverAnalysisTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.result = cx_driver_analysis.run(validate_cx_data.load_rows())

    def test_driver_table_has_inference_columns_and_is_ranked(self):
        drivers = self.result["drivers"]
        self.assertGreater(len(drivers), 8)
        expected = {"dimension", "level", "n", "satisfied_rate", "diff_vs_rest",
                    "diff_ci", "z", "p_value", "cohens_h", "effect", "significant"}
        for d in drivers:
            self.assertTrue(expected.issubset(d))
        magnitudes = [abs(d["cohens_h"]) for d in drivers]
        self.assertEqual(magnitudes, sorted(magnitudes, reverse=True))
        self.assertTrue(any(d["significant"] for d in drivers))

    def test_first_time_owners_is_the_recovered_at_risk_segment(self):
        top = self.result["top_negative_driver"]
        self.assertIsNotNone(top)
        self.assertEqual(top["dimension"], "segment")
        self.assertEqual(top["level"], "First-Time Owners")
        self.assertLess(top["diff_vs_rest"], 0)
        self.assertTrue(top["significant"])
        seg_rates = {
            d["level"]: d["satisfied_rate"]
            for d in self.result["drivers"]
            if d["dimension"] == "segment"
        }
        self.assertEqual(min(seg_rates, key=seg_rates.get), "First-Time Owners")

    def test_completed_follow_up_improves_post_action_outcome(self):
        coh = self.result["follow_up_cohort"]
        self.assertGreater(
            coh["completed_post_satisfied_rate"], coh["open_post_satisfied_rate"]
        )
        self.assertTrue(coh["significant"])
        self.assertGreater(coh["completed_mean_delta"], coh["open_mean_delta"])

    def test_comment_themes_are_extracted(self):
        themes = self.result["comment_themes"]
        self.assertTrue(themes)
        for t in themes:
            self.assertTrue(0.0 <= t["share"] <= 1.0)
            self.assertTrue(1.0 <= t["avg_satisfaction"] <= 5.0)

    def test_nps_is_well_formed_and_recovers_at_risk_segment(self):
        nps = self.result["nps"]
        ov = nps["overall"]
        self.assertEqual(ov["promoters"] + ov["passives"] + ov["detractors"], ov["n"])
        self.assertTrue(-100.0 <= ov["nps"] <= 100.0)
        self.assertLessEqual(ov["nps_ci_95"][0], ov["nps"])
        self.assertGreaterEqual(ov["nps_ci_95"][1], ov["nps"])
        by_seg = nps["by_segment"]
        self.assertEqual({s["segment"] for s in by_seg}, SEGMENTS)
        worst = min(by_seg, key=lambda s: s["nps"])
        self.assertEqual(worst["segment"], "First-Time Owners")

    def test_multivariate_model_controls_for_confounders(self):
        mv = self.result["multivariate_drivers"]
        names = {c["feature"] for c in mv["coefficients"]}
        self.assertIn("intercept", names)
        self.assertIn("friction_score_z", names)
        fric = next(c for c in mv["coefficients"] if c["feature"] == "friction_score_z")
        # friction lowers P(satisfied) and is significant after controlling
        self.assertLess(fric["odds_ratio"], 1.0)
        self.assertTrue(fric["significant"])
        # First-Time Owners is the dropped reference; every significant
        # segment effect is protective (OR > 1) relative to it
        self.assertEqual(mv["reference_levels"]["segment"], "First-Time Owners")
        seg_sig = [
            c for c in mv["coefficients"]
            if c["feature"].startswith("segment=") and c["significant"]
        ]
        self.assertTrue(seg_sig)
        self.assertTrue(all(c["odds_ratio"] > 1.0 for c in seg_sig))


if __name__ == "__main__":
    unittest.main()
